[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''Card = Moveable:extend()'''
position = "before"
payload = '''

---@class CardConfigCenter
---@field key string?
---@field name string?
---@field effect CardEffectName?
---@field alerted boolean?
---@field order number?
---@field set CardTypeName?
---@field atlas string?
---@field consumeable CardConfigCenter?
---@field demo boolean?
---@field unlocked boolean?
---@field discovered boolean?
---@field pos {x:number,y:number}?
---@field pixel_size {w:number,h:number}?
---@field display_size {w:number,h:number}?
---@field set_sprites (fun(self:self,card:Card,front:unknown))?
---@field soul_pos {x:number,y:number}?
---@field blueprint_compat boolean?
---@field eternal_compat boolean?
---@field perishable_compat boolean?
---@field no_suit boolean?
---@field no_rank boolean?
---@field replace_base_card boolean?
---@field rarity (1|2|3|4)?
---@field undiscovered CardConfigCenter?
---@field hc_atlas string?
---@field lc_atlas string?
---@field no_overlay boolean?
---@field max number?
---@field min number?
---@field freq number?
---@field line string?
---@field label string?
---@field available boolean?
---@field kind CardBoosterKindName?
---@field weight number?
---@field start_alerted boolean?
---@field cost number?
---@field cost_mult number?
---@field config EventQuery?
---@field wip boolean?
---@field skip_pool boolean?
---@field omit boolean?

---@class CardConfig
---@field card P_CARDS_VALUE|Card
---@field center CardConfigCenter
---@field card_key string?
---@field center_key string?

---comment
---@class Card: Moveable
---@field params {playing_card: boolean?,viewed_back: boolean?,bypass_discovery_center: boolean?,bypass_discovery_ui: boolean?,bypass_lock: boolean?,bypass_back: boolean?,discover: boolean?}
---@field getting_sliced boolean
---@field ability CardConfigCenter|EventQuery
---@field area CardArea
---@field config CardConfig
---@operator call:Card'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:set_base(card, initial)'''
position = "before"
payload = '''---comment
---@param card Card|P_CARDS_VALUE
---@param initial boolean'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:get_chip_x_mult(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:get_end_of_round_effect(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:can_sell_card(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:calculate_seal(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:calculate_joker(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1