[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''Card = Moveable:extend()'''
position = "before"
payload = '''
---@alias AbilityNames ("swap"|"level_up"|"chips"|"chip_mod"|"bonus"|"s_chips"|"s_chip_mod"|"t_chips"|"t_chip_mod"|"h_chips"|"h_chip_mod"|"x_chips"|"x_chip_mod"|"xchips"|"xchip_mod"|"Xchips"|"Xchip_mod"|"s_x_chips"|"s_x_chip_mod"|"t_x_chips"|"t_x_chip_mod"|"h_x_chips"|"h_x_chip_mod"|"mult"|"mult_mod"|"s_mult"|"s_mult_mod"|"t_mult"|"t_mult_mod"|"h_mult"|"h_mult_mod"|"x_mult"|"x_mult_mod"|"xmult"|"xmult_mod"|"Xmult"|"Xmult_mod"|"s_x_mult"|"s_x_mult_mod"|"t_x_mult"|"t_x_mult_mod"|"h_x_mult"|"h_x_mult_mod"|"dollars"|"h_dollars"|"p_dollars"|"interest_cap"|"interest_gain"|"interest_amount"|"debt_size"|"h_plays"|"d_size"|"h_size"|"h_mod"|"odds_bonus"|"odds_mult"|"free_rerolls"|"hand_add"|"discard_sub"|"increase"|"mod_conv"|"suit_conv"|"remove_card"|"extra_hand_bonus"|"extra_discard_bonus"|"no_interest"|"joker_slot"|"consumeable_slot"|"voucher"|"vouchers"|"consumeable"|"consumeables"|"spectral_rate"|"remove_faces"|"hand_size"|"ante_scaling"|"randomize_rank_suit"|"spawn_jokers"|"skip_bonus"|"forced_selection"|"perma_bonus")

_G.AbilityNames = {
    ["swap"] = false,
    ["level_up"] = 0,
    ["chips"] = 0,
    ["chip_mod"] = 0,
    ["bonus"] = 0,
    ["s_chips"] = 0,
    ["s_chip_mod"] = 0,
    ["t_chips"] = 0,
    ["t_chip_mod"] = 0,
    ["h_chips"] = 0,
    ["h_chip_mod"] = 0,
    ["x_chips"] = 1,
    ["x_chip_mod"] = 0,
    ["xchips"] = 1,
    ["xchip_mod"] = 0,
    ["Xchips"] = 1,
    ["Xchip_mod"] = 0,
    ["s_x_chips"] = 1,
    ["s_x_chip_mod"] = 0,
    ["t_x_chips"] = 1,
    ["t_x_chip_mod"] = 0,
    ["h_x_chips"] = 1,
    ["h_x_chip_mod"] = 0,
    ["mult"] = 0,
    ["mult_mod"] = 0,
    ["s_mult"] = 0,
    ["s_mult_mod"] = 0,
    ["t_mult"] = 0,
    ["t_mult_mod"] = 0,
    ["h_mult"] = 0,
    ["h_mult_mod"] = 0,
    ["x_mult"] = 1,
    ["x_mult_mod"] = 0,
    ["xmult"] = 1,
    ["xmult_mod"] = 0,
    ["Xmult"] = 1,
    ["Xmult_mod"] = 0,
    ["s_x_mult"] = 1,
    ["s_x_mult_mod"] = 0,
    ["t_x_mult"] = 1,
    ["t_x_mult_mod"] = 0,
    ["h_x_mult"] = 1,
    ["h_x_mult_mod"] = 0,
    ["dollars"] = 0,
    ["h_dollars"] = 0,
    ["p_dollars"] = 0,
    ["interest_cap"] = 0,
    ["interest_gain"] = 0,
    ["interest_amount"] = 0,
    ["debt_size"] = 0,
    ["h_plays"] = 0,
    ["d_size"] = 0,
    ["h_size"] = 0,
    ["h_mod"] = 0,
    ["odds_bonus"] = 0,
    ["odds_mult"] = 1,
    ["free_rerolls"] = 0,
    ["hand_add"] = 0,
    ["discard_sub"] = 0,
    ["increase"] = 0,
    ["mod_conv"] = "",
    ["suit_conv"] = "",
    ["remove_card"] = false,
    ["extra_hand_bonus"] = 0,
    ["extra_discard_bonus"] = 0,
    ["no_interest"] = false,
    ["joker_slot"] = 0,
    ["consumeable_slot"] = 0,
    ["voucher"] = "",
    ["vouchers"] = {},
    ["consumeable"] = "",
    ["consumeables"] = {},
    ["spectral_rate"] = 0,
    ["remove_faces"] = false,
    ["hand_size"] = 0,
    ["ante_scaling"] = 1,
    ["randomize_rank_suit"] = false,
    ["spawn_jokers"] = 0,
    ["skip_bonus"] = 0,
    ["forced_selection"] = false,
    ["perma_bonus"] = 0,
}

---@alias AbilityDataNames ("previous_odds"|"extra_value"|"rental"|"invis_rounds"|"to_do_poker_hand"|"caino_xmult"|"yorick_discards"|"burnt_hand"|"loyalty_remaining"|"hands_played_at_create"|"couponed")

_G.AbilityDataNames = {
    ["previous_odds"] = {},
    ["extra_value"] = 0,
    ["rental"] = false,
    ["invis_rounds"] = 0,
    ["to_do_poker_hand"] = undefined,
    ["caino_xmult"] = 1,
    ["yorick_discards"] = 0,
    ["burnt_hand"] = 0,
    ["loyalty_remaining"] = 0,
    ["hands_played_at_create"] = 0,
    ["couponed"] = false,
}

---@alias CardTypeName ("Default"|"Enhanced"|"Joker"|"Edition"|"Tarot"|"Planet"|"Voucher"|"Spectral"|"Booster"|"Back"|"None")
---@alias CardSuitName ("Hearts"|"Clubs"|"Diamonds"|"Spades")
---@alias CardRankName ("2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"10"|"Jack"|"Queen"|"King"|"Ace")
---@alias CardWholeName ("2 of Hearts"|"3 of Hearts"|"4 of Hearts"|"5 of Hearts"|"6 of Hearts"|"7 of Hearts"|"8 of Hearts"|"9 of Hearts"|"10 of Hearts"|"Jack of Hearts"|"Queen of Hearts"|"King of Hearts"|"Ace of Hearts"|"2 of Clubs"|"3 of Clubs"|"4 of Clubs"|"5 of Clubs"|"6 of Clubs"|"7 of Clubs"|"8 of Clubs"|"9 of Clubs"|"10 of Clubs"|"Jack of Clubs"|"Queen of Clubs"|"King of Clubs"|"Ace of Clubs"|"2 of Diamonds"|"3 of Diamonds"|"4 of Diamonds"|"5 of Diamonds"|"6 of Diamonds"|"7 of Diamonds"|"8 of Diamonds"|"9 of Diamonds"|"10 of Diamonds"|"Jack of Diamonds"|"Queen of Diamonds"|"King of Diamonds"|"Ace of Diamonds"|"2 of Spades"|"3 of Spades"|"4 of Spades"|"5 of Spades"|"6 of Spades"|"7 of Spades"|"8 of Spades"|"9 of Spades"|"10 of Spades"|"Jack of Spades"|"Queen of Spades"|"King of Spades"|"Ace of Spades")
---@alias CardEffectName ("Base"|"Mult"|"Suit Mult"|"Type Mult"|"Hand Size Mult"|"Hand card double"|"Credit"|"Discard Chips"|"No Discard Mult"|"Stone card hands"|"1 in 10 mult"|"Spawn Tarot"|"Random Mult"|"Socialized Mult"|"Bonus Rerolls"|"Card Mult"|"Steel Card Buff"|"Scary Face Cards"|"Joker Mult"|"Discard dollars"|"Low Card double"|"All face cards"|"Even Card Buff"|"Odd Card Buff"|"Ace Buff"|"Face Card dollar Chance"|"Hand played mult"|"Upgrade Hand chance"|"Hand Size"|"Discard Size"|"Stone Card Buff"|"Bonus dollars"|"dollars for Gold cards"|"Prevent Death"|"Shop size"|"Face card double"|"Set Mult"|"Hand Size, Plays"|"Glass Card"|"Copycat"|"X1.5 Mult club 7"|"Jack Discard Effect"|"X1.5 Mult"|"X2 Mult"|"X3 Mult"|"Tarot Buff"|"Disable Blind Effect"|"Enhance"|"Round Bonus"|"Dollar Doubler"|"Card Removal"|"Card Conversion"|"Joker Payout"|"Suit Conversion"|"Hand Upgrade"|"Unlocker"|"Bonus Card"|"Mult Card"|"Wild Card"|"Steel Card"|"Stone Card"|"Gold Card"|"Lucky Card"|"")
---@alias CardJokerName ("Default Base"|"Joker"|"Greedy Joker"|"Lusty Joker"|"Wrathful Joker"|"Gluttonous Joker"|"Jolly Joker"|"Zany Joker"|"Mad Joker"|"Crazy Joker"|"Droll Joker"|"Sly Joker"|"Wily Joker"|"Clever Joker"|"Devious Joker"|"Crafty Joker"|"Half Joker"|"Joker Stencil"|"Four Fingers"|"Mime"|"Credit Card"|"Ceremonial Dagger"|"Banner"|"Mystic Summit"|"Marble Joker"|"Loyalty Card"|"8 Ball"|"Misprint"|"Dusk"|"Raised Fist"|"Chaos the Clown"|"Fibonacci"|"Steel Joker"|"Scary Face"|"Abstract Joker"|"Delayed Gratification"|"Hack"|"Pareidolia"|"Gros Michel"|"Even Steven"|"Odd Todd"|"Scholar"|"Business Card"|"Supernova"|"Ride the Bus"|"Space Joker"|'Egg'|'Burglar'|'Blackboard'|'Runner'|'Ice Cream'|'DNA'|'Splash'|'Blue Joker'|'Sixth Sense'|'Constellation'|'Hiker'|'Faceless Joker'|'Green Joker'|'Superposition'|'To Do List'|"Cavendish"|"Card Sharp"|"Red Card"|"Madness"|"Square Joker"|"Seance"|"Riff-raff"|"Vampire"|"Shortcut"|"Hologram"|"Vagabond"|"Baron"|"Cloud 9"|"Rocket"|"Obelisk"|"Midas Mask"|"Luchador"|"Photograph"|"Gift Card"|"Turtle Bean"|"Erosion"|"Reserved Parking"|"Mail-In Rebate"|"To the Moon"|"Hallucination"|"Fortune Teller"|"Juggler"|"Drunkard"|"Stone Joker"|"Golden Joker"|"Lucky Cat"|"Baseball Card"|"Bull"|"Diet Cola"|"Trading Card"|"Flash Card"|"Popcorn"|"Spare Trousers"|"Ancient Joker"|"Ramen"|"Walkie Talkie"|"Seltzer"|"Castle"|"Smiley Face"|"Campfire"|"Golden Ticket"|"Mr. Bones"|"Acrobat"|"Sock and Buskin"|"Swashbuckler"|"Troubadour"|"Certificate"|"Smeared Joker"|"Throwback"|"Hanging Chad"|"Rough Gem"|"Bloodstone"|"Arrowhead"|"Onyx Agate"|"Glass Joker"|"Showman"|"Flower Pot"|"Blueprint"|"Wee Joker"|"Merry Andy"|"Oops! All 6s"|"The Idol"|"Seeing Double"|"Matador"|"Hit the Road"|"The Duo"|"The Trio"|"The Family"|"The Order"|"The Tribe"|"Stuntman"|"Invisible Joker"|"Brainstorm"|"Satellite"|"Shoot the Moon"|"Driver's License"|"Cartomancer"|"Astronomer"|"Burnt Joker"|"Bootstraps"|"Caino"|"Triboulet"|"Yorick"|"Chicot"|"Perkeo"|"The Fool"|"The Magician"|"The High Priestess"|"The Empress"|"The Emperor"|"The Hierophant"|"The Lovers"|"The Chariot"|"Justice"|"The Hermit"|"The Wheel of Fortune"|"Strength"|"The Hanged Man"|"Death"|"Temperance"|"The Devil"|"The Tower"|"The Star"|"The Moon"|"The Sun"|"Judgement"|"The World"|"Mercury"|"Venus"|"Earth"|"Mars"|"Jupiter"|"Saturn"|"Uranus"|"Neptune"|"Pluto"|"Planet X"|"Ceres"|"Eris"|"Familiar"|"Grim"|"Incantation"|"Talisman"|"Aura"|"Wraith"|"Sigil"|"Ouija"|"Ectoplasm"|"Immolate"|"Ankh"|"Deja Vu"|"Hex"|"Trance"|"Medium"|"Cryptid"|"The Soul"|"Black Hole"|"Overstock"|"Clearance Sale"|"Hone"|"Reroll Surplus"|"Crystal Ball"|"Telescope"|"Grabber"|"Wasteful"|"Tarot Merchant"|"Planet Merchant"|"Seed Money"|"Blank"|"Magic Trick"|"Hieroglyph"|"Director's Cut"|"Paint Brush"|"Overstock Plus"|"Liquidation"|"Glow Up"|"Reroll Glut"|"Omen Globe"|"Observatory"|"Nacho Tong"|"Recyclomancy"|"Tarot Tycoon"|"Planet Tycoon"|"Money Tree"|"Antimatter"|"Illusion"|"Petroglyph"|"Retcon"|"Palette"|"Red Deck"|"Blue Deck"|"Yellow Deck"|"Green Deck"|"Black Deck"|"Magic Deck"|"Nebula Deck"|"Ghost Deck"|"Abandoned Deck"|"Checkered Deck"|"Zodiac Deck"|"Painted Deck"|"Anaglyph Deck"|"Plasma Deck"|"Erratic Deck"|"Challenge Deck"|"Bonus"|"Mult"|"Wild Card"|"Glass Card"|"Steel Card"|"Stone Card"|"Gold Card"|"Lucky Card"|"Base"|"Foil"|"Holographic"|"Polychrome"|"Negative"|"Arcana Pack"|"Jumbo Arcana Pack"|"Mega Arcana Pack"|"Celestial Pack"|"Jumbo Celestial Pack"|"Mega Celestial Pack"|"Spectral Pack"|"Jumbo Spectral Pack"|"Mega Spectral Pack"|"Standard Pack"|"Jumbo Standard Pack"|"Mega Standard Pack"|"Buffoon Pack"|"Jumbo Buffoon Pack"|"Mega Buffoon Pack"|string)
---@alias CardEnhancementName ("m_bonus"|"m_mult"|"m_wild"|"m_glass"|"m_steel"|"m_stone"|"m_gold"|"m_lucky")
---@alias CardSealName ("Gold"|"Red"|"Blue"|"Purple")
---@alias CardBoosterKindName ("Arcana"|"Spectral"|"Celestial"|"Standard"|"Buffoon")
---@alias PokerHandName ("High Card"|"Pair"|"Two Pair"|"Three of a Kind"|"Straight"|"Flush"|"Four of a Kind"|"Full House"|"Straight Flush"|"Five of a Kind"|"Flush House"|"Flush Five")
---@alias VoucherName ("v_overstock_norm"|"v_clearance_sale"|"v_hone"|"v_reroll_surplus"|"v_crystal_ball"|"v_telescope"|"v_grabber"|"v_wasteful"|"v_tarot_merchant"|"v_planet_merchant"|"v_seed_money"|"v_blank"|"v_magic_trick"|"v_hieroglyph"|"v_directors_cut"|"v_paint_brush"|"v_overstock_plus"|"v_liquidation"|"v_glow_up"|"v_reroll_glut"|"v_omen_globe"|"v_observatory"|"v_nacho_tong"|"v_recyclomancy"|"v_tarot_tycoon"|"v_planet_tycoon"|"v_money_tree"|"v_antimatter"|"v_illusion"|"v_petroglyph"|"v_retcon"|"v_palette")
---@alias ConsumeableName ("c_fool"|"c_magician"|"c_high_priestess"|"c_empress"|"c_emperor"|"c_heirophant"|"c_lovers"|"c_chariot"|"c_justice"|"c_hermit"|"c_wheel_of_fortune"|"c_strength"|"c_hanged_man"|"c_death"|"c_temperance"|"c_devil"|"c_tower"|"c_star"|"c_moon"|"c_sun"|"c_judgement"|"c_world"|"c_mercury"|"c_venus"|"c_earth"|"c_mars"|"c_jupiter"|"c_saturn"|"c_uranus"|"c_neptune"|"c_pluto"|"c_planet_x"|"c_ceres"|"c_eris"|"c_familiar"|"c_grim"|"c_incantation"|"c_talisman"|"c_aura"|"c_wraith"|"c_sigil"|"c_ouija"|"c_ectoplasm"|"c_immolate"|"c_ankh"|"c_deja_vu"|"c_hex"|"c_trance"|"c_medium"|"c_cryptid"|"c_soul"|"c_black_hole")
---@alias TagEffectTimingName ('store_joker_create'|'store_joker_modify'|'eval'|'voucher_add'|'new_blind_choice'|'immediate'|'shop_final_pass'|'tag_add'|'round_start_bonus'|'shop_start')

---@class CardConfigCenter
---@field key string?
---@field name string?
---@field effect CardEffectName?
---@field alerted boolean?
---@field order number?
---@field set CardTypeName?
---@field atlas string?
---@field consumeable CardConfigCenter?
---@field demo boolean?
---@field unlocked boolean?
---@field discovered boolean?
---@field pos {x:number,y:number}?
---@field pixel_size {w:number,h:number}?
---@field display_size {w:number,h:number}?
---@field set_sprites (fun(self:self,card:Card,front:unknown))?
---@field soul_pos {x:number,y:number}?
---@field blueprint_compat boolean?
---@field eternal_compat boolean?
---@field perishable_compat boolean?
---@field no_suit boolean?
---@field no_rank boolean?
---@field replace_base_card boolean?
---@field rarity (1|2|3|4)?
---@field undiscovered CardConfigCenter?
---@field hc_atlas string?
---@field lc_atlas string?
---@field no_overlay boolean?
---@field max number?
---@field min number?
---@field freq number?
---@field line string?
---@field label string?
---@field available boolean?
---@field kind CardBoosterKindName?
---@field weight number?
---@field start_alerted boolean?
---@field cost number?
---@field cost_mult number?
---@field config EventQuery?
---@field wip boolean?
---@field skip_pool boolean?
---@field omit boolean?

---@class CardConfig
---@field card P_CARDS_VALUE|Card
---@field center CardConfigCenter
---@field card_key string?
---@field center_key string?
---@field h_popup UIElement?
---@field h_popup_config UIElement?

---comment
---@class Card: Moveable
---@field params {playing_card: boolean?,viewed_back: boolean?,bypass_discovery_center: boolean?,bypass_discovery_ui: boolean?,bypass_lock: boolean?,bypass_back: boolean?,discover: boolean?}
---@field getting_sliced boolean
---@field ability CardConfigCenter|EventQuery
---@field area CardArea
---@field config CardConfig
---@operator call:Card'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:set_base(card, initial)'''
position = "before"
payload = '''---comment
---@param card Card|P_CARDS_VALUE
---@param initial boolean'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:get_chip_x_mult(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:get_end_of_round_effect(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:can_sell_card(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:calculate_seal(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''function Card:calculate_joker(context)'''
position = "before"
payload = '''---comment
---@param context GameEventContext
---@return unknown, unknown|nil'''
match_indent = true
times = 1