[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "Game = Object:extend()"
position = "before"
payload = '''
---@class Game: Object
---@operator call(...):Game
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "    self.P_CARDS = {"
position = "before"
payload = '''
---@enum (key) PlayingCardName
'''
match_indent = true
times = 1
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "    self.P_CENTERS = {"
position = "before"
payload = '''
---@enum (key) CardNameStrict
'''
match_indent = true
times = 1